name: vf
favicon: null
layout_spectrum: 0
typography_spectrum: 0.70112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#291f2a'
    - '#d3c0b1'
    - '#bd9482'
    - '#55414c'
    - '#c7645f'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
