name: vf
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#910745'
    - '#ffffff'
    - '#fd7e23'
    - '#eab0ad'
    - '#ed2e29'
  brandStrength: 0.7261278876103461
  lightness: 0.875
  saturation: 0.9758422719314694
  rhythmicContrast: 1
purpose: []
